### ISSUE TITLE
RHEL minimal install: missing tar

### ISSUE THREAD

**Issue by deajan** [carlocorradini/node_exporter_installer#25]
Hello,

When using the following on a fresh minimal RHEL 9.0 install
```
curl -sSfL https://raw.githubusercontent.com/carlocorradini/node_exporter_installer/main/install.sh | sh - && systemctl enable --now node_exporter```
```
I get the following output: `[FATAL] Command 'tar' not found`

Can indeed be mitigated by `dnf install -y tar`

Do you think that could be automated in the script ?

Best regards.

**Comment by carlocorradini** [comment]
This is distribution-specific.
The script must be distribution-agnostic; otherwise, it would have to support every possible package manager (and configuration).
I'm not very familiar with RHEL; does it already have something installed that can deal with `tar` files (not `tar` program)? Even `Alpine Linux` (~125MB) has `tar` preinstalled :/
.
Note that the behavior of `systemctl` can be customized (see <https://github.com/carlocorradini/node_exporter_installer/blob/main/install.sh> usage comment). Therefore, `systemctl enable --now node_exporter` can be removed :)

**Comment by deajan** [comment]
tar doesn't come with minimal installation of RHEL (not a surprise, it says minimal).

Distribution agnostic doesn't mean it cannot be added.
It would be pretty easy to add a distribution specific fix, eg `type -p yum > /dev/null 2>&1 && yum install -y tar` without interfering with other distributions.

As for the `systemctl enable --now`, indeed, didn't read.

**Comment by carlocorradini** [comment]
I don't want to automatically force the installation of required commands and programs. Also, this is distribution-specific because each one comes with a different package manager, package name, and configuration.
Rather, I prefer to inform the user with an error message and exit with a code different from `0`.
Moreover, I think it's far easier to simply run the following command:
```console
yum install -y tar \
  && curl -sSfL https://raw.githubusercontent.com/carlocorradini/node_exporter_installer/main/install.sh \
  && echo "Node exporter installed successfully"
```

**Comment by deajan** [comment]
Well it's your script.

**Comment by carlocorradini** [comment]
I want collaboration and help :)
Unfortunately I think this is a specific case that can be solved by a simple yum install.

**Comment by deajan** [comment]
No problem ;)
